import ApplicationFormModel from "./applicationFormModel";
const {
  formField: {
    firstName,
    email,
    lastName,
    city,
    zipcode,
    country,
    astate,
    occupation,
    income,
    bio,
    loanAmount,
    loanCategory,
    loanDescription,
    loanDuration,
    loanDurationUnit,
    repaymentStartDate,
    emiRepetition,
    guarantor,
    imgURL,
    idNumber,
    idDoc,
  },
} = ApplicationFormModel;

const DefaultFields = {
  [firstName.name]: "",
  [lastName.name]: "",
  [email.name]: "",
  [city.name]: "",
  [zipcode.name]: "",
  [country.name]: "",
  [astate.name]: "",
  [occupation.name]: "",
  [bio.name]: "",
  [income.name]: "",
  [loanAmount.name]: "",
  [loanCategory.name]: "",
  [loanDescription.name]: "",
  [loanDuration.name]: "",
  [loanDurationUnit.name]: "",
  [repaymentStartDate.name]: "",
  [emiRepetition.name]: "",
  [guarantor.name]: "",
  [imgURL.name]: "",
  [idDoc.name]: "",
  [idNumber.name]: "",
};
export default DefaultFields;
