export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const GET_USER = "GET_USER";
export const LOADING_USER = "LOADING_USER";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_ERROR_LOGIN = "SET_ERROR_LOGIN";
export const SET_ERROR_SIGNUP = "SET_ERROR_SIGNUP";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
